# Generated by Django 4.2.16 on 2025-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_coupon_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
