# Generated by Django 4.2.16 on 2025-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_stripe_coupon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
