# Generated by Django 4.2.16 on 2025-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="promotion_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
