# Generated by Django 4.2.16 on 2025-10-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_promotion_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="promotion_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
