# Generated by Django 5.1.7 on 2026-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_coupon_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_account_admin",
            field=models.BooleanField(default=False),
        ),
    ]
