# Generated by Django 5.1.7 on 2026-08-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_subscription_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="signup_ip_address",
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
    ]
