# Generated by Django 5.1.7 on 2026-08-20 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0009_qualification_employeequalification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="data_imports/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CSV", "CSV"),
                            ("XLSX", "Excel"),
                            ("XLS", "Excel 97-2003"),
                            ("DAT", "DAT"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("target_model", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("ANALYZING", "Analyzing"),
                            ("MAPPING", "Mapping"),
                            ("VALIDATING", "Validating"),
                            ("READY", "Ready"),
                            ("IMPORTING", "Importing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_imports",
                        to="app.company",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataImportColumn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_column", models.CharField(max_length=255)),
                ("target_field", models.CharField(max_length=255)),
                ("column_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=False)),
                ("is_mapped", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="dataintegration.dataimport",
                    ),
                ),
            ],
            options={
                "ordering": ["column_order"],
            },
        ),
        migrations.AddIndex(
            model_name="dataimport",
            index=models.Index(
                fields=["company", "status"], name="dataintegra_company_db52ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataimport",
            index=models.Index(
                fields=["company", "-created_at"], name="dataintegra_company_54e79c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataimport",
            index=models.Index(
                fields=["uploaded_by", "-created_at"],
                name="dataintegra_uploade_e8b79a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataimportcolumn",
            index=models.Index(
                fields=["data_import", "column_order"],
                name="dataintegra_data_im_aca1d8_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataimportcolumn",
            constraint=models.UniqueConstraint(
                fields=("data_import", "source_column"),
                name="unique_import_source_column",
            ),
        ),
    ]
