# Generated by Django 5.1.7 on 2026-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataintegration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimportcolumn",
            name="is_mapped",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dataimportcolumn",
            name="target_field",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
