# Generated by Django 5.1.7 on 2026-09-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataintegration", "0002_alter_dataimportcolumn_is_mapped_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("ANALYZING", "Analyzing"),
                    ("MAPPING", "Mapping"),
                    ("VALIDATING", "Validating"),
                    ("READY", "Ready"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="UPLOADED",
                max_length=20,
            ),
        ),
    ]
