# Generated by Django 4.2.16 on 2025-09-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prospects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="business_type",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospect",
            name="company_size",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospect",
            name="contact",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospect",
            name="products",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prospect",
            name="website",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
