# Generated by Django 5.1.7 on 2026-08-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactusrequest",
            name="company_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactusrequest",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
