# Generated by Django 5.1.7 on 2026-08-09 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contactusrequest_company_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactusrequest",
            old_name="name",
            new_name="first_name",
        ),
    ]
