# Generated by Django 4.2.16 on 2025-11-02 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_costsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="app.company",
            ),
        ),
    ]
