# Generated by Django 4.2.16 on 2025-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_equipment_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="loc_last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
