# Generated by Django 4.2.16 on 2025-11-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_equipment_latitude_equipment_loc_last_updated_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="codename",
            new_name="callsign",
        ),
        migrations.AddField(
            model_name="employee",
            name="level",
            field=models.CharField(
                choices=[
                    ("2", "Level 2"),
                    ("3", "Level 3"),
                    ("4", "Level 4"),
                    ("5+", "Level 5+"),
                ],
                default="2",
                max_length=3,
            ),
        ),
    ]
