# Generated by Django 5.1.7 on 2025-11-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_codename_employee_callsign_employee_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="service_request_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
