# Generated by Django 5.1.7 on 2026-07-18 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_servicerequest_service_request_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("certification", "Certification"),
                            ("license", "License"),
                            ("medical", "Medical"),
                            ("equipment", "Equipment"),
                            ("other", "Other"),
                        ],
                        default="training",
                        max_length=50,
                    ),
                ),
                (
                    "rep_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of repetitions or renewals required.",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("required_approval", models.BooleanField(default=False)),
                ("field_1", models.CharField(blank=True, max_length=255, null=True)),
                ("field_2", models.CharField(blank=True, max_length=255, null=True)),
                ("field_3", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Qualification",
                "verbose_name_plural": "Qualifications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeQualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_qualifications",
                        to="app.employee",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_qualifications",
                        to="app.qualification",
                    ),
                ),
            ],
            options={
                "ordering": ["qualification__name"],
                "unique_together": {("employee", "qualification")},
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                through="app.EmployeeQualification",
                to="app.qualification",
            ),
        ),
    ]
