# Generated by Django 5.1.7 on 2026-09-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_qualification_employeequalification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_requests",
                to="app.company",
            ),
        ),
    ]
