# Generated by Django 5.1.7 on 2026-09-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_servicerequest_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="service_requests",
                to="app.company",
            ),
        ),
    ]
