# Generated by Django 5.1.7 on 2026-09-29 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_servicerequest_company"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeequalification",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="employeequalification",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="employeequalification",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="employeequalification",
            name="qualification",
        ),
    ]
