# Generated by Django 5.1.7 on 2026-09-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_alter_employeequalification_unique_together_and_more"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="employees",
                through="training.EmployeeQualification",
                to="training.qualification",
            ),
        ),
        migrations.DeleteModel(
            name="EmployeeQualification",
        ),
        migrations.DeleteModel(
            name="Qualification",
        ),
    ]
