# Generated by Django 5.1.7 on 2026-10-05 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_employee_qualifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetype",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_types",
                to="app.company",
            ),
        ),
    ]
