# Generated by Django 5.1.7 on 2026-10-05 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_servicetype_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="employee",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="manager_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manager_employee_service_requests",
                to="app.employee",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="assigned_employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_employee_service_requests",
                to="app.employee",
            ),
        ),
    ]
