# Generated by Django 5.1.7 on 2026-10-05 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_servicerequest_employee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="assigned_employees",
        ),
        migrations.CreateModel(
            name="AssignedEmployee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_employees",
                        to="app.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_employee_service_requests",
                        to="app.employee",
                    ),
                ),
                (
                    "service_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_employees",
                        to="app.servicerequest",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("service_request", "employee"),
                        name="unique_assigned_employee_per_service_request",
                    )
                ],
            },
        ),
    ]
