# Generated by Django 4.2.16 on 2025-09-09 00:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("opened", models.BooleanField(default=False)),
                ("opened_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
