# Generated by Django 4.2.16 on 2025-11-11 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ip_whitelist1", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipwhitelist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whitelisted_ips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
