# Generated by Django 5.1.7 on 2026-08-09 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_whitelist1", "0003_alter_ipwhitelist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocked_ipaddress",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
