# Generated by Django 4.2.16 on 2026-08-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_whitelist1', '0004_blocked_ipaddress_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocked_ipaddress',
            name='reason',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
