# Generated by Django 5.1.7 on 2026-09-19 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0009_qualification_employeequalification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            (
                                "employees_per_service_request",
                                "Employees per Service Request",
                            ),
                            (
                                "profitability_per_service_request",
                                "Profitability per Service Request",
                            ),
                            (
                                "service_requests_per_customer",
                                "Service Requests per Customer",
                            ),
                            (
                                "location_profitability",
                                "Revenue and Profitability per Location",
                            ),
                            ("custom", "Custom Model Report"),
                        ],
                        default="custom",
                        max_length=100,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("selected_columns", models.JSONField(blank=True, default=list)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("sort_field", models.CharField(blank=True, max_length=100)),
                (
                    "sort_direction",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        max_length=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_definitions",
                        to="app.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "created_by", "name"),
                        name="unique_saved_report_per_user_company",
                    )
                ],
            },
        ),
    ]
