# Generated by Django 4.2.16 on 2025-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_alter_product_options_product_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote_number",
            field=models.CharField(max_length=20),
        ),
    ]
