# Generated by Django 5.1.7 on 2026-09-23 21:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_servicerequest_company"),
        ("business", "0010_invoice_company_alter_customer_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Customer number must contain only letters and numbers and be 6 to 16 characters long.",
                        regex="^[A-Za-z0-9]{6,16}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("company", "customer_number"),
                name="unique_customer_number_per_company",
            ),
        ),
    ]
