# Generated by Django 4.2.16 on 2025-10-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priceanalysis", "0002_analysis_state_analysis_zipprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis_ZipCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=5, unique=True)),
                ("state_code", models.CharField(max_length=2)),
            ],
        ),
    ]
