# Generated by Django 4.2.16 on 2025-09-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order_number", "name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Controls display order in store",
                null=True,
            ),
        ),
    ]
