# Generated by Django 4.2.16 on 2025-10-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0005_alter_quote_quote_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote_number",
            field=models.CharField(max_length=20),
        ),
    ]
