# Generated by Django 4.2.16 on 2025-10-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_alter_quote_quote_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
