# Generated by Django 5.1.7 on 2026-09-20 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_servicerequest_company"),
        ("business", "0009_customer_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_customers",
                to="app.company",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company_customers",
                to="app.company",
            ),
        ),
    ]
