# Generated by Django 5.1.7 on 2026-09-23 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0011_customer_customer_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="addres_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("BILLING", "Billing"),
                    ("SHIPPING", "Shipping"),
                    ("MAILING", "Mailing"),
                    ("OTHER", "Other"),
                ],
                default="MAILING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, default="United States", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
