# Generated by Django 5.1.7 on 2026-09-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_customer_addres_list_customer_address_line_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="addres_list",
            new_name="address_list",
        ),
    ]
