# Generated by Django 4.2.16 on 2025-10-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_stripe_transaction"),
        ("userpayment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="app.company",
            ),
        ),
    ]
