# Generated by Django 4.2.16 on 2025-10-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpayment", "0003_userpayment_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpayment",
            name="stripe_checkout_id",
        ),
        migrations.AddField(
            model_name="userpayment",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="userpayment",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
