# Generated by Django 4.2.16 on 2025-10-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userpayment", "0004_remove_userpayment_stripe_checkout_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpayment",
            name="stripe_checkout_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
