# Generated by Django 4.2.16 on 2026-03-14 17:09

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video",
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
