# Generated by Django 5.1.7 on 2026-07-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_qualification_employeequalification_and_more"),
        ("video", "0002_video_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="app.company",
            ),
        ),
    ]
