# Generated by Django 4.2.16 on 2025-09-09 00:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("format_type", models.CharField(blank=True, max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFileAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "file_type",
                    models.CharField(help_text="MIME type or extension", max_length=50),
                ),
                (
                    "num_columns",
                    models.PositiveIntegerField(
                        help_text="Number of columns in the file"
                    ),
                ),
                (
                    "num_rows",
                    models.PositiveIntegerField(help_text="Number of rows in the file"),
                ),
                (
                    "column_headers",
                    models.JSONField(default=list, help_text="List of column names"),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="dataupload.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
